USE MASTER

IF EXISTS(SELECT * FROM SYS.DATABASES WHERE NAME='DB')
BEGIN 
	ALTER DATABASE DB SET SINGLE_USER WITH ROLLBACK IMMEDIATE

	DROP DATABASE DB
END

CREATE DATABASE DB
GO

USE DB

CREATE TABLE PESSOA
(
	COD_PESSOA INT IDENTITY PRIMARY KEY,
	NOME_PESSOA VARCHAR(50) UNIQUE NOT NULL,
	SALARIO_PESSOA DECIMAL(9, 2)
)

INSERT PESSOA
VALUES ('ADAO', 1000),
	('EVA', 500),
	('CAIM', 10),
	('ABEL', 10),
	('SETH', 10)
